CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE locations (
    id uuid NOT NULL,
    code character varying(40) NOT NULL,
    aisle character varying(10),
    shelf smallint,
    level_number smallint,
    pallet_position character varying(10),
    description character varying(200),
    is_blocked boolean NOT NULL DEFAULT FALSE,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_locations" PRIMARY KEY (id),
    CONSTRAINT ck_locations_level CHECK (level_number IS NULL OR level_number > 0),
    CONSTRAINT ck_locations_shelf CHECK (shelf IS NULL OR shelf > 0)
);

CREATE TABLE roles (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(30) NOT NULL,
    name character varying(80) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_roles" PRIMARY KEY (id)
);

CREATE TABLE units (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(20) NOT NULL,
    name character varying(80) NOT NULL,
    allows_decimals boolean NOT NULL DEFAULT TRUE,
    is_active boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_units" PRIMARY KEY (id)
);

CREATE TABLE users (
    id uuid NOT NULL,
    full_name character varying(160) NOT NULL,
    role_id smallint NOT NULL,
    pin_lookup character(64) NOT NULL,
    pin_hash text NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    failed_pin_attempts smallint NOT NULL DEFAULT 0,
    locked_until timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_users" PRIMARY KEY (id),
    CONSTRAINT ck_users_failed_pin_attempts CHECK (failed_pin_attempts >= 0),
    CONSTRAINT "FK_users_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT
);

CREATE TABLE products (
    id uuid NOT NULL,
    sku character varying(60) NOT NULL,
    name character varying(180) NOT NULL,
    description text,
    type_code character varying(40),
    class_code character varying(60),
    base_unit_id smallint NOT NULL,
    minimum_stock numeric(18,4) NOT NULL,
    tracks_lots boolean NOT NULL DEFAULT FALSE,
    tracks_expiration boolean NOT NULL DEFAULT FALSE,
    allows_negative_stock boolean NOT NULL DEFAULT TRUE,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_products" PRIMARY KEY (id),
    CONSTRAINT ck_products_expiration_requires_lots CHECK (NOT tracks_expiration OR tracks_lots),
    CONSTRAINT ck_products_minimum_stock CHECK (minimum_stock >= 0),
    CONSTRAINT "FK_products_units_base_unit_id" FOREIGN KEY (base_unit_id) REFERENCES units (id) ON DELETE RESTRICT
);

CREATE TABLE product_barcodes (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    barcode character varying(100) NOT NULL,
    format character varying(30) NOT NULL DEFAULT 'CODE_128',
    is_primary boolean NOT NULL DEFAULT FALSE,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_product_barcodes" PRIMARY KEY (id),
    CONSTRAINT ck_product_barcodes_format CHECK (format IN ('CODE_128', 'EAN_13', 'EAN_8', 'UPC_A', 'UPC_E', 'QR', 'OTHER')),
    CONSTRAINT "FK_product_barcodes_products_product_id" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

INSERT INTO roles (id, code, created_at, name)
VALUES (1, 'ADMIN', TIMESTAMPTZ '1970-01-01T00:00:00+00:00', 'Administrador');
INSERT INTO roles (id, code, created_at, name)
VALUES (2, 'OPERATOR', TIMESTAMPTZ '1970-01-01T00:00:00+00:00', 'Operador');

INSERT INTO units (id, code, is_active, name)
VALUES (1, 'EA', TRUE, 'Pieza');

CREATE UNIQUE INDEX "IX_locations_code" ON locations (code);

CREATE UNIQUE INDEX "IX_product_barcodes_barcode" ON product_barcodes (barcode);

CREATE UNIQUE INDEX "IX_product_barcodes_product_id" ON product_barcodes (product_id) WHERE is_primary = TRUE;

CREATE INDEX "IX_products_base_unit_id" ON products (base_unit_id);

CREATE UNIQUE INDEX "IX_products_sku" ON products (sku);

CREATE UNIQUE INDEX "IX_roles_code" ON roles (code);

CREATE UNIQUE INDEX "IX_units_code" ON units (code);

CREATE UNIQUE INDEX "IX_users_pin_lookup" ON users (pin_lookup);

CREATE INDEX "IX_users_role_id" ON users (role_id);

SELECT setval(
    pg_get_serial_sequence('roles', 'id'),
    GREATEST(
        (SELECT MAX(id) FROM roles) + 1,
        nextval(pg_get_serial_sequence('roles', 'id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('units', 'id'),
    GREATEST(
        (SELECT MAX(id) FROM units) + 1,
        nextval(pg_get_serial_sequence('units', 'id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260813150854_InitialSchema', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE users DROP CONSTRAINT ck_users_failed_pin_attempts;

ALTER TABLE users DROP COLUMN failed_pin_attempts;

ALTER TABLE users DROP COLUMN locked_until;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260813153505_RemovePinLockout', '10.0.10');

COMMIT;

START TRANSACTION;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM products) THEN
        RAISE EXCEPTION 'CatalogsAndProductReference requiere que products esté vacío.';
    END IF;
END $$;

ALTER TABLE products DROP COLUMN class_code;

ALTER TABLE products DROP COLUMN type_code;

ALTER TABLE products ADD external_reference character varying(120);

ALTER TABLE products ADD product_class_id smallint;

ALTER TABLE products ADD product_type_id smallint;

CREATE TABLE product_classes (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(60) NOT NULL,
    name character varying(100) NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_product_classes" PRIMARY KEY (id),
    CONSTRAINT ck_product_classes_code_normalized CHECK (code = upper(btrim(code)) AND code <> '')
);

CREATE TABLE product_types (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(40) NOT NULL,
    name character varying(100) NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_product_types" PRIMARY KEY (id),
    CONSTRAINT ck_product_types_code_normalized CHECK (code = upper(btrim(code)) AND code <> '')
);

INSERT INTO product_classes (id, code, is_active, name)
VALUES (1, '2-BBAGS', TRUE, '2-BBAGS');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (2, 'AQUA', TRUE, 'AQUA');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (3, 'AQUATANK', TRUE, 'AQUATANK');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (4, 'BAYRIG', TRUE, 'BAYRIG');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (5, 'BCF', TRUE, 'BCF');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (6, 'BERMS', TRUE, 'BERMS');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (7, 'BIOSEAL', TRUE, 'BIOSEAL');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (8, 'BIOSEAL-EPI', TRUE, 'BIOSEAL-EPI');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (9, 'BODY BAGS', TRUE, 'BODY BAGS');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (10, 'BODY BAGS-HARD BAGS', TRUE, 'BODY BAGS-HARD BAGS');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (11, 'CBF', TRUE, 'CBF');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (12, 'DUMPSTER LINER', TRUE, 'DUMPSTER LINER');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (13, 'FC-HARDBAGS', TRUE, 'FC-HARDBAGS');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (14, 'IWM', TRUE, 'IWM');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (15, 'KPA', TRUE, 'KPA');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (16, 'MISC', TRUE, 'MISC');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (17, 'NUCLEAR BAGS', TRUE, 'NUCLEAR BAGS');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (18, 'PACKAGING', TRUE, 'PACKAGING');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (19, 'RAD BAGS', TRUE, 'RAD BAGS');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (20, 'RM', TRUE, 'RM');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (21, 'SPOUTED BAGS', TRUE, 'SPOUTED BAGS');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (22, 'SUB', TRUE, 'SUB');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (23, 'SUB-COMP', TRUE, 'SUB-COMP');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (24, 'SUBASS', TRUE, 'SUBASS');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (25, 'SUBASSEMBLY', TRUE, 'SUBASSEMBLY');
INSERT INTO product_classes (id, code, is_active, name)
VALUES (26, 'UNDERGARMENTS', TRUE, 'UNDERGARMENTS');

INSERT INTO product_types (id, code, is_active, name)
VALUES (1, 'FG', TRUE, 'Producto terminado');
INSERT INTO product_types (id, code, is_active, name)
VALUES (2, 'RAW', TRUE, 'Materia prima');

INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (2, TRUE, 'BX', TRUE, 'Caja');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (3, TRUE, 'BDL', TRUE, 'Bulto');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (4, TRUE, 'CTN', TRUE, 'Caja de embarque');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (5, TRUE, 'FT', TRUE, 'Pie');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (6, TRUE, 'GAL', TRUE, 'Galón');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (7, TRUE, '5GAL', TRUE, 'Recipiente de 5 galones');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (8, TRUE, '3GANG', TRUE, 'Grupo de 3');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (9, TRUE, 'KT', TRUE, 'Kit');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (10, TRUE, 'PR', TRUE, 'Par');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (11, TRUE, 'LB', TRUE, 'Libra');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (12, TRUE, 'RL', TRUE, 'Rollo');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (13, TRUE, 'SQFT', TRUE, 'Pie cuadrado');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (14, TRUE, 'MSI', TRUE, 'Mil pulgadas cuadradas');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (15, TRUE, 'YD', TRUE, 'Yarda');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (16, TRUE, 'IN', TRUE, 'Pulgada');
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (17, TRUE, 'OZ', TRUE, 'Onza');

UPDATE units SET allows_decimals = TRUE
WHERE id = 1;

SELECT setval(pg_get_serial_sequence('units', 'id'), (SELECT MAX(id) FROM units), true);
SELECT setval(pg_get_serial_sequence('product_types', 'id'), (SELECT MAX(id) FROM product_types), true);
SELECT setval(pg_get_serial_sequence('product_classes', 'id'), (SELECT MAX(id) FROM product_classes), true);

ALTER TABLE units ADD CONSTRAINT ck_units_code_normalized CHECK (code = upper(btrim(code)) AND code <> '');

CREATE INDEX "IX_products_product_class_id" ON products (product_class_id);

CREATE INDEX "IX_products_product_type_id" ON products (product_type_id);

ALTER TABLE products ADD CONSTRAINT ck_products_external_reference_trimmed CHECK (external_reference IS NULL OR (external_reference = btrim(external_reference) AND external_reference <> ''));

ALTER TABLE products ADD CONSTRAINT ck_products_sku_normalized CHECK (sku = upper(btrim(sku)) AND sku <> '');

CREATE UNIQUE INDEX "IX_product_classes_code" ON product_classes (code);

CREATE UNIQUE INDEX "IX_product_types_code" ON product_types (code);

ALTER TABLE products ADD CONSTRAINT "FK_products_product_classes_product_class_id" FOREIGN KEY (product_class_id) REFERENCES product_classes (id) ON DELETE RESTRICT;

ALTER TABLE products ADD CONSTRAINT "FK_products_product_types_product_type_id" FOREIGN KEY (product_type_id) REFERENCES product_types (id) ON DELETE RESTRICT;

SELECT setval(
    pg_get_serial_sequence('product_classes', 'id'),
    GREATEST(
        (SELECT MAX(id) FROM product_classes) + 1,
        nextval(pg_get_serial_sequence('product_classes', 'id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('product_types', 'id'),
    GREATEST(
        (SELECT MAX(id) FROM product_types) + 1,
        nextval(pg_get_serial_sequence('product_types', 'id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('units', 'id'),
    GREATEST(
        (SELECT MAX(id) FROM units) + 1,
        nextval(pg_get_serial_sequence('units', 'id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260813171350_CatalogsAndProductReference', '10.0.10');

COMMIT;

START TRANSACTION;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.products) THEN
        RAISE EXCEPTION 'RemoveProductName requires public.products to be empty.';
    END IF;
END $$;

ALTER TABLE products DROP COLUMN name;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260813175106_RemoveProductName', '10.0.10');

COMMIT;

START TRANSACTION;
INSERT INTO units (id, allows_decimals, code, is_active, name)
VALUES (18, TRUE, 'UNASSIGNED', TRUE, 'Sin asignar');

SELECT setval(
    pg_get_serial_sequence('units', 'id'),
    GREATEST(
        (SELECT MAX(id) FROM units) + 1,
        nextval(pg_get_serial_sequence('units', 'id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260813185432_AddUnassignedUnit', '10.0.10');

COMMIT;

START TRANSACTION;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM locations) THEN
        RAISE EXCEPTION 'LocationLayoutStructure requiere locations vacía para evitar reinterpretar ubicaciones provisionales.';
    END IF;
END $$;

ALTER TABLE locations DROP CONSTRAINT ck_locations_level;

ALTER TABLE locations DROP CONSTRAINT ck_locations_shelf;

ALTER TABLE locations DROP COLUMN aisle;

ALTER TABLE locations DROP COLUMN pallet_position;

ALTER TABLE locations RENAME COLUMN shelf TO rack_number;

ALTER TABLE locations RENAME COLUMN level_number TO pallet_number;

ALTER TABLE locations ADD block_reason character varying(200);

ALTER TABLE locations ADD kind character varying(10) NOT NULL;

ALTER TABLE locations ADD row_code character varying(1);

CREATE UNIQUE INDEX "IX_locations_row_code_rack_number_pallet_number" ON locations (row_code, rack_number, pallet_number) WHERE kind = 'RACK';

ALTER TABLE locations ADD CONSTRAINT ck_locations_block CHECK ((is_blocked = FALSE AND block_reason IS NULL) OR (is_active = TRUE AND is_blocked = TRUE AND block_reason IS NOT NULL AND btrim(block_reason) <> ''));

ALTER TABLE locations ADD CONSTRAINT ck_locations_code_normalized CHECK (code = upper(btrim(code)) AND code <> '');

ALTER TABLE locations ADD CONSTRAINT ck_locations_kind CHECK (kind IN ('RACK', 'AREA'));

ALTER TABLE locations ADD CONSTRAINT ck_locations_structure CHECK ((kind = 'RACK' AND row_code ~ '^[A-Z]$' AND rack_number > 0 AND pallet_number BETWEEN 1 AND 9 AND code = row_code || '-' || rack_number::text || '-' || pallet_number::text) OR (kind = 'AREA' AND row_code IS NULL AND rack_number IS NULL AND pallet_number IS NULL AND code ~ '^[A-Z0-9]([A-Z0-9-]*[A-Z0-9])?$'));

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260814121053_LocationLayoutStructure', '10.0.10');

COMMIT;

START TRANSACTION;
CREATE TABLE product_location_assignments (
    product_id uuid NOT NULL,
    location_id uuid NOT NULL,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_product_location_assignments" PRIMARY KEY (product_id, location_id),
    CONSTRAINT "FK_product_location_assignments_locations_location_id" FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_product_location_assignments_products_product_id" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_product_location_assignments_location_id" ON product_location_assignments (location_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260814124317_ProductLocationAssignments', '10.0.10');

COMMIT;

START TRANSACTION;
ALTER TABLE products DROP COLUMN allows_negative_stock;

CREATE TABLE inventory_movements (
    id uuid NOT NULL,
    operation_id uuid NOT NULL,
    request_fingerprint character(64) NOT NULL,
    type character varying(20) NOT NULL,
    responsible_user_id uuid NOT NULL,
    reference character varying(120),
    notes character varying(500),
    occurred_at timestamp with time zone NOT NULL DEFAULT (now()),
    recorded_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_inventory_movements" PRIMARY KEY (id),
    CONSTRAINT ck_inventory_movements_type CHECK (type IN ('ENTRY', 'EXIT', 'TRANSFER', 'ADJUSTMENT')),
    CONSTRAINT "FK_inventory_movements_users_responsible_user_id" FOREIGN KEY (responsible_user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE TABLE product_lots (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    number character varying(100) NOT NULL,
    normalized_number character varying(100) NOT NULL,
    expiration_date date,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_product_lots" PRIMARY KEY (id),
    CONSTRAINT ck_product_lots_normalized_number CHECK (normalized_number = upper(btrim(normalized_number)) AND normalized_number <> ''),
    CONSTRAINT "FK_product_lots_products_product_id" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT
);

CREATE TABLE inventory_balances (
    id uuid NOT NULL,
    product_id uuid NOT NULL,
    location_id uuid NOT NULL,
    lot_id uuid,
    quantity numeric(18,4) NOT NULL,
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_inventory_balances" PRIMARY KEY (id),
    CONSTRAINT "FK_inventory_balances_locations_location_id" FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_balances_product_lots_lot_id" FOREIGN KEY (lot_id) REFERENCES product_lots (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_balances_products_product_id" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT
);

CREATE TABLE inventory_movement_lines (
    id uuid NOT NULL,
    movement_id uuid NOT NULL,
    line_number integer NOT NULL,
    product_id uuid NOT NULL,
    unit_id smallint NOT NULL,
    quantity numeric(18,4) NOT NULL,
    source_location_id uuid,
    destination_location_id uuid,
    lot_id uuid,
    previous_quantity numeric(18,4),
    adjustment_delta numeric(18,4),
    CONSTRAINT "PK_inventory_movement_lines" PRIMARY KEY (id),
    CONSTRAINT ck_inventory_movement_lines_number CHECK (line_number > 0),
    CONSTRAINT "FK_inventory_movement_lines_inventory_movements_movement_id" FOREIGN KEY (movement_id) REFERENCES inventory_movements (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_movement_lines_locations_destination_location_id" FOREIGN KEY (destination_location_id) REFERENCES locations (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_movement_lines_locations_source_location_id" FOREIGN KEY (source_location_id) REFERENCES locations (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_movement_lines_product_lots_lot_id" FOREIGN KEY (lot_id) REFERENCES product_lots (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_movement_lines_products_product_id" FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_movement_lines_units_unit_id" FOREIGN KEY (unit_id) REFERENCES units (id) ON DELETE RESTRICT
);

CREATE TABLE inventory_balance_changes (
    id uuid NOT NULL,
    movement_line_id uuid NOT NULL,
    location_id uuid NOT NULL,
    lot_id uuid,
    delta_quantity numeric(18,4) NOT NULL,
    previous_quantity numeric(18,4) NOT NULL,
    resulting_quantity numeric(18,4) NOT NULL,
    CONSTRAINT "PK_inventory_balance_changes" PRIMARY KEY (id),
    CONSTRAINT ck_inventory_balance_changes_arithmetic CHECK (previous_quantity + delta_quantity = resulting_quantity),
    CONSTRAINT "FK_inventory_balance_changes_inventory_movement_lines_movement~" FOREIGN KEY (movement_line_id) REFERENCES inventory_movement_lines (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_balance_changes_locations_location_id" FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_balance_changes_product_lots_lot_id" FOREIGN KEY (lot_id) REFERENCES product_lots (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_inventory_balance_changes_location_id" ON inventory_balance_changes (location_id);

CREATE INDEX "IX_inventory_balance_changes_lot_id" ON inventory_balance_changes (lot_id);

CREATE INDEX "IX_inventory_balance_changes_movement_line_id" ON inventory_balance_changes (movement_line_id);

CREATE INDEX "IX_inventory_balances_location_id" ON inventory_balances (location_id);

CREATE INDEX "IX_inventory_balances_lot_id" ON inventory_balances (lot_id);

CREATE UNIQUE INDEX "IX_inventory_balances_product_id_location_id" ON inventory_balances (product_id, location_id) WHERE lot_id IS NULL;

CREATE UNIQUE INDEX "IX_inventory_balances_product_id_location_id_lot_id" ON inventory_balances (product_id, location_id, lot_id) WHERE lot_id IS NOT NULL;

CREATE INDEX "IX_inventory_balances_quantity" ON inventory_balances (quantity) WHERE quantity < 0;

CREATE INDEX "IX_inventory_movement_lines_destination_location_id" ON inventory_movement_lines (destination_location_id);

CREATE INDEX "IX_inventory_movement_lines_lot_id" ON inventory_movement_lines (lot_id);

CREATE UNIQUE INDEX "IX_inventory_movement_lines_movement_id_line_number" ON inventory_movement_lines (movement_id, line_number);

CREATE INDEX "IX_inventory_movement_lines_product_id" ON inventory_movement_lines (product_id);

CREATE INDEX "IX_inventory_movement_lines_source_location_id" ON inventory_movement_lines (source_location_id);

CREATE INDEX "IX_inventory_movement_lines_unit_id" ON inventory_movement_lines (unit_id);

CREATE INDEX "IX_inventory_movements_occurred_at" ON inventory_movements (occurred_at);

CREATE UNIQUE INDEX "IX_inventory_movements_operation_id" ON inventory_movements (operation_id);

CREATE INDEX "IX_inventory_movements_responsible_user_id_occurred_at" ON inventory_movements (responsible_user_id, occurred_at);

CREATE UNIQUE INDEX "IX_product_lots_product_id_normalized_number" ON product_lots (product_id, normalized_number);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260814142411_InventoryCore', '10.0.10');

COMMIT;

START TRANSACTION;
CREATE TABLE inventory_movement_corrections (
    id uuid NOT NULL,
    operation_id uuid NOT NULL,
    request_fingerprint character(64) NOT NULL,
    type character varying(20) NOT NULL,
    original_movement_id uuid NOT NULL,
    reversal_movement_id uuid NOT NULL,
    replacement_movement_id uuid,
    reason character varying(500) NOT NULL,
    requested_by_user_id uuid NOT NULL,
    authorized_by_user_id uuid NOT NULL,
    recorded_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT "PK_inventory_movement_corrections" PRIMARY KEY (id),
    CONSTRAINT ck_inventory_movement_corrections_type CHECK (type IN ('REVERSAL', 'REPLACEMENT')),
    CONSTRAINT "FK_inventory_movement_corrections_inventory_movements_original_movement_id" FOREIGN KEY (original_movement_id) REFERENCES inventory_movements (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_movement_corrections_inventory_movements_reversal_movement_id" FOREIGN KEY (reversal_movement_id) REFERENCES inventory_movements (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_movement_corrections_inventory_movements_replacement_movement_id" FOREIGN KEY (replacement_movement_id) REFERENCES inventory_movements (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_movement_corrections_users_requested_by_user_id" FOREIGN KEY (requested_by_user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_movement_corrections_users_authorized_by_user_id" FOREIGN KEY (authorized_by_user_id) REFERENCES users (id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_inventory_movement_corrections_operation_id" ON inventory_movement_corrections (operation_id);

CREATE UNIQUE INDEX "IX_inventory_movement_corrections_original_movement_id" ON inventory_movement_corrections (original_movement_id);

CREATE UNIQUE INDEX "IX_inventory_movement_corrections_reversal_movement_id" ON inventory_movement_corrections (reversal_movement_id);

CREATE UNIQUE INDEX "IX_inventory_movement_corrections_replacement_movement_id" ON inventory_movement_corrections (replacement_movement_id) WHERE replacement_movement_id IS NOT NULL;

CREATE INDEX "IX_inventory_movement_corrections_requested_by_user_id" ON inventory_movement_corrections (requested_by_user_id);

CREATE INDEX "IX_inventory_movement_corrections_authorized_by_user_id" ON inventory_movement_corrections (authorized_by_user_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260815090000_InventoryMovementCorrections', '10.0.10');

COMMIT;

