using Microsoft.EntityFrameworkCore;
using WarehouseEPI.Core.Entities;

namespace WarehouseEPI.Infrastructure.Production;

public static partial class ProductionModelConfiguration
{
    private static void ConfigureDailyProduction(ModelBuilder modelBuilder)
    {
        var config = modelBuilder.Entity<ProductionDailyConfiguration>();
        config.ToTable("production_daily_configuration", table => table.HasCheckConstraint("ck_production_daily_configuration_singleton", "id = 1"));
        config.HasKey(x => x.Id);
        config.Property(x => x.Id).HasColumnName("id");
        config.Property(x => x.LastOperationId).HasColumnName("last_operation_id");
        config.Property(x => x.LastRequestFingerprint).HasColumnName("last_request_fingerprint").HasMaxLength(64).IsFixedLength();
        config.Property(x => x.CuttingStageId).HasColumnName("cutting_stage_id");
        config.Property(x => x.SewingStageId).HasColumnName("sewing_stage_id");
        config.Property(x => x.ReadyToPackStageId).HasColumnName("ready_to_pack_stage_id");
        config.Property(x => x.Shift1Id).HasColumnName("shift_1_id");
        config.Property(x => x.Shift2Id).HasColumnName("shift_2_id");
        config.Property(x => x.UpdatedByUserId).HasColumnName("updated_by_user_id");
        config.Property(x => x.UpdatedAt).HasColumnName("updated_at");
        config.Property(x => x.Version).HasColumnName("version").IsConcurrencyToken();
        config.HasOne(x => x.CuttingStage).WithMany().HasForeignKey(x => x.CuttingStageId).OnDelete(DeleteBehavior.Restrict);
        config.HasOne(x => x.SewingStage).WithMany().HasForeignKey(x => x.SewingStageId).OnDelete(DeleteBehavior.Restrict);
        config.HasOne(x => x.ReadyToPackStage).WithMany().HasForeignKey(x => x.ReadyToPackStageId).OnDelete(DeleteBehavior.Restrict);
        config.HasOne(x => x.Shift1).WithMany().HasForeignKey(x => x.Shift1Id).OnDelete(DeleteBehavior.Restrict);
        config.HasOne(x => x.Shift2).WithMany().HasForeignKey(x => x.Shift2Id).OnDelete(DeleteBehavior.Restrict);
        config.HasOne(x => x.UpdatedByUser).WithMany().HasForeignKey(x => x.UpdatedByUserId).OnDelete(DeleteBehavior.Restrict);
        config.HasData(new ProductionDailyConfiguration { Id = 1, Version = 0 });

        var week = modelBuilder.Entity<ProductionScheduleWeek>();
        week.ToTable("production_schedule_weeks", table => table.HasCheckConstraint("ck_production_schedule_week_dates", "week_end = week_start + 5"));
        week.HasKey(x => x.Id);
        week.Property(x => x.Id).HasColumnName("id");
        week.Property(x => x.OperationId).HasColumnName("operation_id");
        week.Property(x => x.RequestFingerprint).HasColumnName("request_fingerprint").HasMaxLength(64).IsFixedLength();
        week.Property(x => x.WeekStart).HasColumnName("week_start");
        week.Property(x => x.WeekEnd).HasColumnName("week_end");
        week.Property(x => x.Status).HasColumnName("status").HasMaxLength(12).HasConversion<string>();
        week.Property(x => x.Origin).HasColumnName("origin").HasMaxLength(16).HasConversion<string>();
        week.Property(x => x.SourceName).HasColumnName("source_name").HasMaxLength(160);
        week.Property(x => x.CreatedByUserId).HasColumnName("created_by_user_id");
        week.Property(x => x.CreatedAt).HasColumnName("created_at");
        week.Property(x => x.PublishedByUserId).HasColumnName("published_by_user_id");
        week.Property(x => x.PublishedAt).HasColumnName("published_at");
        week.Property(x => x.ClosedByUserId).HasColumnName("closed_by_user_id");
        week.Property(x => x.ClosedAt).HasColumnName("closed_at");
        week.Property(x => x.Version).HasColumnName("version").IsConcurrencyToken();
        week.HasIndex(x => x.OperationId).IsUnique();
        week.HasIndex(x => x.WeekStart).IsUnique();
        week.HasOne(x => x.CreatedByUser).WithMany().HasForeignKey(x => x.CreatedByUserId).OnDelete(DeleteBehavior.Restrict);
        week.HasOne(x => x.PublishedByUser).WithMany().HasForeignKey(x => x.PublishedByUserId).OnDelete(DeleteBehavior.Restrict);
        week.HasOne(x => x.ClosedByUser).WithMany().HasForeignKey(x => x.ClosedByUserId).OnDelete(DeleteBehavior.Restrict);

        var line = modelBuilder.Entity<ProductionScheduleLine>();
        line.ToTable("production_schedule_lines", table => table.HasCheckConstraint("ck_production_schedule_line_quantity", "quantity > 0"));
        line.HasKey(x => x.Id);
        line.Property(x => x.IsExtra).HasColumnName("is_extra");
        line.Property(x => x.Id).HasColumnName("id");
        line.Property(x => x.WeekId).HasColumnName("week_id");
        line.Property(x => x.Sequence).HasColumnName("sequence");
        line.Property(x => x.PlannedDate).HasColumnName("planned_date");
        line.Property(x => x.ProductId).HasColumnName("product_id");
        line.Property(x => x.Quantity).HasColumnName("quantity").HasPrecision(18, 4);
        line.Property(x => x.OrderReference1).HasColumnName("order_reference_1").HasMaxLength(120);
        line.Property(x => x.OrderReference2).HasColumnName("order_reference_2").HasMaxLength(120);
        line.Property(x => x.OrderReference3).HasColumnName("order_reference_3").HasMaxLength(120);
        line.Property(x => x.Notes).HasColumnName("notes").HasMaxLength(500);
        line.Property(x => x.Origin).HasColumnName("origin").HasMaxLength(16).HasConversion<string>();
        line.Property(x => x.IsCarryover).HasColumnName("is_carryover");
        line.Property(x => x.StartArea).HasColumnName("start_area").HasMaxLength(20).HasConversion<string>();
        line.Property(x => x.WorkOrderId).HasColumnName("work_order_id");
        line.Property(x => x.SourceSheet).HasColumnName("source_sheet").HasMaxLength(120);
        line.Property(x => x.SourceRow).HasColumnName("source_row");
        line.Property(x => x.IsCancelled).HasColumnName("is_cancelled");
        line.Property(x => x.Version).HasColumnName("version").IsConcurrencyToken();
        line.HasIndex(x => new { x.WeekId, x.Sequence }).IsUnique();
        line.HasIndex(x => x.WorkOrderId).IsUnique().HasFilter("work_order_id IS NOT NULL");
        line.HasIndex(x => new { x.ProductId, x.PlannedDate });
        line.HasOne(x => x.Week).WithMany(x => x.Lines).HasForeignKey(x => x.WeekId).OnDelete(DeleteBehavior.Restrict);
        line.HasOne(x => x.Product).WithMany().HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.Restrict);
        line.HasOne(x => x.WorkOrder).WithMany().HasForeignKey(x => x.WorkOrderId).OnDelete(DeleteBehavior.Restrict);

        var revision = modelBuilder.Entity<ProductionScheduleRevision>();
        revision.ToTable("production_schedule_revisions");
        revision.HasKey(x => x.Id);
        revision.Property(x => x.Id).HasColumnName("id");
        revision.Property(x => x.OperationId).HasColumnName("operation_id");
        revision.Property(x => x.RequestFingerprint).HasColumnName("request_fingerprint").HasMaxLength(64).IsFixedLength();
        revision.Property(x => x.WeekId).HasColumnName("week_id");
        revision.Property(x => x.LineId).HasColumnName("line_id");
        revision.Property(x => x.Action).HasColumnName("action").HasMaxLength(30);
        revision.Property(x => x.BeforeJson).HasColumnName("before_json").HasColumnType("jsonb");
        revision.Property(x => x.AfterJson).HasColumnName("after_json").HasColumnType("jsonb");
        revision.Property(x => x.ResponsibleUserId).HasColumnName("responsible_user_id");
        revision.Property(x => x.RecordedAt).HasColumnName("recorded_at");
        revision.HasIndex(x => x.OperationId).IsUnique();
        revision.HasIndex(x => new { x.WeekId, x.RecordedAt });
        revision.HasOne(x => x.Week).WithMany(x => x.Revisions).HasForeignKey(x => x.WeekId).OnDelete(DeleteBehavior.Restrict);
        revision.HasOne(x => x.ResponsibleUser).WithMany().HasForeignKey(x => x.ResponsibleUserId).OnDelete(DeleteBehavior.Restrict);

        var capture = modelBuilder.Entity<ProductionDailyCapture>();
        capture.ToTable("production_daily_captures", table => table.HasCheckConstraint("ck_production_daily_capture_quantity", "quantity > 0"));
        capture.HasKey(x => x.Id);
        capture.Property(x => x.IsFlexible).HasColumnName("is_flexible");
        capture.Property(x => x.ReverseOperationId).HasColumnName("reverse_operation_id");
        capture.Property(x => x.ReverseFingerprint).HasColumnName("reverse_fingerprint").HasMaxLength(64);
        capture.HasIndex(x => x.ReverseOperationId).IsUnique();
        capture.Property(x => x.Id).HasColumnName("id");
        capture.Property(x => x.OperationId).HasColumnName("operation_id");
        capture.Property(x => x.RequestFingerprint).HasColumnName("request_fingerprint").HasMaxLength(64).IsFixedLength();
        capture.Property(x => x.WeekId).HasColumnName("week_id");
        capture.Property(x => x.EffectiveDate).HasColumnName("effective_date");
        capture.Property(x => x.Area).HasColumnName("area").HasMaxLength(20).HasConversion<string>();
        capture.Property(x => x.StageId).HasColumnName("stage_id");
        capture.Property(x => x.ShiftId).HasColumnName("shift_id");
        capture.Property(x => x.ProductId).HasColumnName("product_id");
        capture.Property(x => x.Quantity).HasColumnName("quantity").HasPrecision(18, 4);
        capture.Property(x => x.Notes).HasColumnName("notes").HasMaxLength(500);
        capture.Property(x => x.Origin).HasColumnName("origin").HasMaxLength(16).HasConversion<string>();
        capture.Property(x => x.ImportedReporter).HasColumnName("imported_reporter").HasMaxLength(160);
        capture.Property(x => x.SourceSheet).HasColumnName("source_sheet").HasMaxLength(120);
        capture.Property(x => x.SourceRow).HasColumnName("source_row");
        capture.Property(x => x.ResponsibleUserId).HasColumnName("responsible_user_id");
        capture.Property(x => x.RecordedAt).HasColumnName("recorded_at");
        capture.Property(x => x.Status).HasColumnName("status").HasMaxLength(12).HasConversion<string>();
        capture.Property(x => x.ReversedByUserId).HasColumnName("reversed_by_user_id");
        capture.Property(x => x.ReversedAt).HasColumnName("reversed_at");
        capture.Property(x => x.ReverseReason).HasColumnName("reverse_reason").HasMaxLength(500);
        capture.HasIndex(x => x.OperationId).IsUnique();
        capture.HasIndex(x => new { x.WeekId, x.EffectiveDate, x.ProductId });
        capture.HasOne(x => x.Week).WithMany(x => x.Captures).HasForeignKey(x => x.WeekId).OnDelete(DeleteBehavior.Restrict);
        capture.HasOne(x => x.Stage).WithMany().HasForeignKey(x => x.StageId).OnDelete(DeleteBehavior.Restrict);
        capture.HasOne(x => x.Shift).WithMany().HasForeignKey(x => x.ShiftId).OnDelete(DeleteBehavior.Restrict);
        capture.HasOne(x => x.Product).WithMany().HasForeignKey(x => x.ProductId).OnDelete(DeleteBehavior.Restrict);
        capture.HasOne(x => x.ResponsibleUser).WithMany().HasForeignKey(x => x.ResponsibleUserId).OnDelete(DeleteBehavior.Restrict);
        capture.HasOne(x => x.ReversedByUser).WithMany().HasForeignKey(x => x.ReversedByUserId).OnDelete(DeleteBehavior.Restrict);

        var allocation = modelBuilder.Entity<ProductionDailyCaptureAllocation>();
        allocation.ToTable("production_daily_capture_allocations", table => table.HasCheckConstraint("ck_production_daily_capture_allocation_quantity", "quantity > 0"));
        allocation.HasKey(x => x.Id);
        allocation.Property(x => x.ReconciledAt).HasColumnName("reconciled_at");
        allocation.Property(x => x.ReconciledByUserId).HasColumnName("reconciled_by_user_id");
        allocation.HasOne<User>().WithMany().HasForeignKey(x => x.ReconciledByUserId).OnDelete(DeleteBehavior.Restrict);
        allocation.Property(x => x.Id).HasColumnName("id");
        allocation.Property(x => x.CaptureId).HasColumnName("capture_id");
        allocation.Property(x => x.ScheduleLineId).HasColumnName("schedule_line_id");
        allocation.Property(x => x.WorkOrderId).HasColumnName("work_order_id");
        allocation.Property(x => x.WorkOrderStageId).HasColumnName("work_order_stage_id");
        allocation.Property(x => x.BatchResultId).HasColumnName("batch_result_id");
        allocation.Property(x => x.Quantity).HasColumnName("quantity").HasPrecision(18, 4);
        allocation.Property(x => x.ProcessOperationId).HasColumnName("process_operation_id");
        allocation.Property(x => x.DeliveryOperationId).HasColumnName("delivery_operation_id");
        allocation.Property(x => x.ReceiveOperationId).HasColumnName("receive_operation_id");
        allocation.HasIndex(x => x.ProcessOperationId).IsUnique();
        allocation.HasIndex(x => x.BatchResultId).IsUnique().HasFilter("batch_result_id IS NOT NULL");
        allocation.HasOne(x => x.Capture).WithMany(x => x.Allocations).HasForeignKey(x => x.CaptureId).OnDelete(DeleteBehavior.Cascade);
        allocation.HasOne(x => x.ScheduleLine).WithMany(x => x.CaptureAllocations).HasForeignKey(x => x.ScheduleLineId).OnDelete(DeleteBehavior.Restrict);
        allocation.HasOne(x => x.WorkOrder).WithMany().HasForeignKey(x => x.WorkOrderId).OnDelete(DeleteBehavior.Restrict);
        allocation.HasOne(x => x.WorkOrderStage).WithMany().HasForeignKey(x => x.WorkOrderStageId).OnDelete(DeleteBehavior.Restrict);
        allocation.HasOne(x => x.BatchResult).WithMany().HasForeignKey(x => x.BatchResultId).OnDelete(DeleteBehavior.Restrict);

        var import = modelBuilder.Entity<ProductionScheduleImportBatch>();
        import.ToTable("production_schedule_import_batches");
        import.HasKey(x => x.Id);
        import.Property(x => x.Id).HasColumnName("id");
        import.Property(x => x.OperationId).HasColumnName("operation_id");
        import.Property(x => x.RequestFingerprint).HasColumnName("request_fingerprint").HasMaxLength(64).IsFixedLength();
        import.Property(x => x.FileHash).HasColumnName("file_hash").HasMaxLength(64).IsFixedLength();
        import.Property(x => x.FileName).HasColumnName("file_name").HasMaxLength(255);
        import.Property(x => x.ImportedByUserId).HasColumnName("imported_by_user_id");
        import.Property(x => x.ImportedAt).HasColumnName("imported_at");
        import.Property(x => x.WeekCount).HasColumnName("week_count");
        import.Property(x => x.LineCount).HasColumnName("line_count");
        import.Property(x => x.CaptureCount).HasColumnName("capture_count");
        import.Property(x => x.ResolutionSummary).HasColumnName("resolution_summary");
        import.HasIndex(x => x.OperationId).IsUnique();
        import.HasIndex(x => x.FileHash).IsUnique();
        import.HasOne(x => x.ImportedByUser).WithMany().HasForeignKey(x => x.ImportedByUserId).OnDelete(DeleteBehavior.Restrict);
    }
}
