using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WarehouseEPI.Core.Entities;
using WarehouseEPI.Infrastructure.Production;
namespace WarehouseEPI.Web.Pages.Operations.Production;
public sealed class WorkModel(ProductionQueryService query,ProductionService service):PageModel
{
 public ProductionOrderDetail Order{get;private set;}=null!;public IReadOnlyList<ProductionShift> Shifts{get;private set;}=[];public IReadOnlyList<Location> Destinations{get;private set;}=[];
 [BindProperty]public ProcessInput Process{get;set;}=new();[BindProperty]public HandoffInput Handoff{get;set;}=new();[BindProperty]public WarehouseInput Warehouse{get;set;}=new();[BindProperty]public ActionInput Action{get;set;}=new();
 public async Task<IActionResult> OnGetAsync(Guid id,CancellationToken t)=>await LoadAsync(id,t)?Page():NotFound();
 public async Task<IActionResult> OnPostProcessAsync(Guid id,CancellationToken t){ModelState.Clear();var r=await service.ProcessAsync(new(Process.OperationId,id,Process.StageId,Process.ShiftId,Process.IsRework,Process.InputQuantity,Process.GoodQuantity,Process.ReworkQuantity,Process.ScrapQuantity,Process.Reason,Process.Pin),t);Process.Pin="";return await Finish(id,r,"Avance registrado.",t);}
 public async Task<IActionResult> OnPostHandoffAsync(Guid id,CancellationToken t){ModelState.Clear();var c=new ProductionHandoffCommand(Handoff.OperationId,id,Handoff.SourceStageId,Handoff.TargetStageId,Handoff.Quantity,Handoff.Pin,Handoff.Reason);var r=Handoff.Mode switch{"deliver"=>await service.DeliverAsync(c,t),"receive"=>await service.ReceiveAsync(c,t),"return"=>await service.ReturnDifferenceAsync(c,t),"lost"=>await service.LoseDifferenceAsync(c,t),_=>new(ProductionCommandStatus.ValidationFailed,Errors:["Acción no válida."])};Handoff.Pin="";return await Finish(id,r,"Movimiento entre etapas registrado.",t);}
 public async Task<IActionResult> OnPostWarehouseAsync(Guid id,CancellationToken t){ModelState.Clear();var r=await service.ReceiveWarehouseAsync(new(Warehouse.OperationId,id,Warehouse.FinalStageId,Warehouse.Quantity,Warehouse.DestinationLocationId,Warehouse.Pin),t);Warehouse.Pin="";if(r.Status==ProductionCommandStatus.Success&&r.MovementId is Guid m){TempData["Success"]="Producto recibido y Entrada registrada.";return RedirectToPage("/Operations/Receipt",new{id=m});}return await Finish(id,r,"Recepción registrada.",t);}
 public async Task<IActionResult> OnPostActionAsync(Guid id,CancellationToken t){ModelState.Clear();var c=new ProductionOrderActionCommand(Action.OperationId,id,Action.ExpectedVersion,Action.Pin,Action.Reason,Action.Quantity);var r=Action.Mode switch{"release"=>await service.ReleaseAsync(c,t),"pause"=>await service.PauseAsync(c,t),"resume"=>await service.ResumeAsync(c,t),"authorize"=>await service.AuthorizeAdditionalAsync(c,t),"close"=>await service.CloseAsync(c,t),"cancel"=>await service.CancelAsync(c,t),_=>new(ProductionCommandStatus.ValidationFailed,Errors:["Acción no válida."])};Action.Pin="";return await Finish(id,r,"Orden actualizada.",t);}
 private async Task<IActionResult> Finish(Guid id,ProductionCommandResult r,string message,CancellationToken t){if(r.Status==ProductionCommandStatus.Success){TempData["Success"]=message;return RedirectToPage(new{id});}ModelState.AddModelError(string.Empty,Message(r));return await InvalidPage(id,t);}
 private async Task<PageResult> InvalidPage(Guid id,CancellationToken t){Process.Pin=Handoff.Pin=Warehouse.Pin=Action.Pin="";await LoadAsync(id,t);return Page();}
 private async Task<bool> LoadAsync(Guid id,CancellationToken t){var o=await query.GetAsync(id,t);if(o is null)return false;Order=o;Shifts=await query.GetShiftsAsync(t);Destinations=await query.GetDestinationsAsync(t);Action.ExpectedVersion=o.Version;return true;}
 private static string Message(ProductionCommandResult r)=>r.Status switch{ProductionCommandStatus.InvalidPin=>"NIP inválido o usuario sin permiso.",ProductionCommandStatus.ConcurrencyConflict=>"La orden cambió mientras capturabas. Recarga y vuelve a revisar las cantidades.",ProductionCommandStatus.IdempotencyConflict=>"Esta operación ya se usó con datos distintos.",ProductionCommandStatus.RequiresLocationSharingConfirmation=>"La ubicación contiene otros productos; confirma desde el flujo de Entrada antes de continuar.",_=>r.ValidationErrors.FirstOrDefault()??"No fue posible registrar la operación."};
 public sealed class ProcessInput{public Guid OperationId{get;set;}=Guid.NewGuid();[Required]public Guid StageId{get;set;}[Required]public Guid ShiftId{get;set;}public bool IsRework{get;set;}[Range(typeof(decimal),"0.0001","99999999999999")]public decimal InputQuantity{get;set;}public decimal GoodQuantity{get;set;}public decimal ReworkQuantity{get;set;}public decimal ScrapQuantity{get;set;}[StringLength(500)]public string? Reason{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
 public sealed class HandoffInput{public Guid OperationId{get;set;}=Guid.NewGuid();[Required]public string Mode{get;set;}="deliver";[Required]public Guid SourceStageId{get;set;}[Required]public Guid TargetStageId{get;set;}[Range(typeof(decimal),"0.0001","99999999999999")]public decimal Quantity{get;set;}[StringLength(500)]public string? Reason{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
 public sealed class WarehouseInput{public Guid OperationId{get;set;}=Guid.NewGuid();[Required]public Guid FinalStageId{get;set;}[Range(typeof(decimal),"0.0001","99999999999999")]public decimal Quantity{get;set;}[Required]public Guid DestinationLocationId{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
 public sealed class ActionInput{public Guid OperationId{get;set;}=Guid.NewGuid();[Required]public string Mode{get;set;}="release";public uint? ExpectedVersion{get;set;}public decimal Quantity{get;set;}[StringLength(500)]public string? Reason{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
}
