using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WarehouseEPI.Core.Entities;
using WarehouseEPI.Infrastructure.Production;
namespace WarehouseEPI.Web.Pages.Operations.Production;
public sealed class WorkModel(ProductionQueryService query,ProductionService service,ProductionMaterialService materials,ProductionTraceabilityService traceability,ProductionPlanningService planning):PageModel
{
 public ProductionPlanningView PlanningView{get;private set;}=new([],[],[],false);
 public ProductionOrderDetail Order{get;private set;}=null!;public IReadOnlyList<ProductionShift> Shifts{get;private set;}=[];public IReadOnlyList<Location> Destinations{get;private set;}=[];public IReadOnlyList<ProductionMaterialIssueRow> MaterialIssues{get;private set;}=[];public IReadOnlyList<ProductionMaterialOperationRow> MaterialOperations{get;private set;}=[];public IReadOnlyList<ProductionBatchView>Batches{get;private set;}=[];public IReadOnlyList<ProductionMaterialPlanView>MaterialPlan{get;private set;}=[];public IReadOnlyList<ProductionDeliveryView>PendingDeliveries{get;private set;}=[];public IReadOnlyList<ProductionTraceLinkView>TraceLinks{get;private set;}=[];public IReadOnlyList<ProductionBatchResultView>BatchResults{get;private set;}=[];[BindProperty(SupportsGet=true)]public Guid? BatchId{get;set;}
 [BindProperty]public ProcessInput Process{get;set;}=new();[BindProperty]public HandoffInput Handoff{get;set;}=new();[BindProperty]public WarehouseInput Warehouse{get;set;}=new();[BindProperty]public ActionInput Action{get;set;}=new();[BindProperty]public MaterialInput Material{get;set;}=new();[BindProperty]public MaterialReverseInput MaterialReverse{get;set;}=new();[BindProperty]public BatchInput Batch{get;set;}=new();[BindProperty]public BatchResultInput BatchResult{get;set;}=new();[BindProperty]public PlanAdjustmentInput PlanAdjustment{get;set;}=new();[BindProperty]public ResultReverseInput ResultReverse{get;set;}=new();
 [BindProperty]public PlanningInput Planning{get;set;}=new();
 public async Task<IActionResult> OnGetAsync(Guid id,CancellationToken t)=>await LoadAsync(id,t)?Page():NotFound();
 public async Task<IActionResult> OnGetPlanningTargetsAsync(Guid stageId,string? q,CancellationToken t){if(!User.IsInRole("ADMIN"))return Forbid();return new JsonResult(await planning.SearchTargetsAsync(stageId,q,t));}
 public async Task<IActionResult> OnPostProcessAsync(Guid id,CancellationToken t){ModelState.Clear();var r=await service.ProcessAsync(new(Process.OperationId,id,Process.StageId,Process.ShiftId,Process.IsRework,Process.InputQuantity,Process.GoodQuantity,Process.ReworkQuantity,Process.ScrapQuantity,Process.Reason,Process.Pin),t);Process.Pin="";return await Finish(id,r,"Avance registrado.",t);}
 public async Task<IActionResult> OnPostHandoffAsync(Guid id,CancellationToken t){ModelState.Clear();var c=new ProductionHandoffCommand(Handoff.OperationId,id,Handoff.SourceStageId,Handoff.TargetStageId,Handoff.Quantity,Handoff.Pin,Handoff.Reason,Handoff.BatchId,Handoff.DeliveryEventId,Handoff.ExpectedVersion);var r=Handoff.Mode switch{"deliver"=>await service.DeliverAsync(c,t),"receive"=>await service.ReceiveAsync(c,t),"return"=>await service.ReturnDifferenceAsync(c,t),"lost"=>await service.LoseDifferenceAsync(c,t),_=>new(ProductionCommandStatus.ValidationFailed,Errors:["Acción no válida."])};Handoff.Pin="";return await Finish(id,r,"Movimiento entre etapas registrado.",t);}
 public async Task<IActionResult> OnPostWarehouseAsync(Guid id,CancellationToken t){ModelState.Clear();var r=await service.ReceiveWarehouseAsync(new(Warehouse.OperationId,id,Warehouse.FinalStageId,Warehouse.Quantity,Warehouse.DestinationLocationId,Warehouse.Pin,BatchId:Warehouse.BatchId,ExpectedVersion:Warehouse.ExpectedVersion),t);Warehouse.Pin="";if(r.Status==ProductionCommandStatus.Success&&r.MovementId is Guid m){TempData["Success"]="Producto recibido y Entrada registrada.";return RedirectToPage("/Operations/Receipt",new{id=m});}return await Finish(id,r,"Recepción registrada.",t);}
 public async Task<IActionResult> OnPostBatchAsync(Guid id,CancellationToken t){ModelState.Clear();var r=await traceability.CreateBatchAsync(new(Batch.OperationId,id,Batch.Quantity,Batch.ExpectedVersion,Batch.Pin),t);Batch.Pin="";if(r.Success){TempData["Success"]="Lote de producción creado.";return RedirectToPage(new{id,BatchId=r.Id});}ModelState.AddModelError(string.Empty,r.Errors?.FirstOrDefault()??"No fue posible crear el lote.");return await InvalidPage(id,t);}
 public async Task<IActionResult> OnPostBatchResultAsync(Guid id,CancellationToken t){ModelState.Clear();var selected=BatchResult.Materials.Where(x=>x.Selected&&x.Quantity>0).Select(x=>new BatchMaterialInput(x.IssueLinkId,x.Quantity)).ToArray();var r=await traceability.RecordResultAsync(new(BatchResult.OperationId,id,BatchResult.BatchId,BatchResult.StageId,BatchResult.ShiftId,BatchResult.IsRework,BatchResult.InputQuantity,BatchResult.GoodQuantity,BatchResult.ReworkQuantity,BatchResult.ScrapQuantity,selected,BatchResult.ExpectedVersion,BatchResult.DifferenceReason,BatchResult.Pin),t);BatchResult.Pin="";if(r.Success){TempData["Success"]="Resultado y consumo registrados.";return RedirectToPage(new{id,BatchId=BatchResult.BatchId});}ModelState.AddModelError(string.Empty,r.Errors?.FirstOrDefault()??"No fue posible registrar el resultado.");return await InvalidPage(id,t);}
 public async Task<IActionResult> OnPostAdjustPlanAsync(Guid id,CancellationToken t){ModelState.Clear();var r=await traceability.AdjustPlanAsync(PlanAdjustment.OperationId,PlanAdjustment.PlanId,PlanAdjustment.Quantity,PlanAdjustment.ExpectedVersion,PlanAdjustment.Reason??"",PlanAdjustment.Pin,t);PlanAdjustment.Pin="";if(r.Success){TempData["Success"]="Plan de material ajustado con motivo.";return RedirectToPage(new{id,BatchId});}ModelState.AddModelError(string.Empty,r.Errors?.FirstOrDefault()??"No fue posible ajustar el plan.");return await InvalidPage(id,t);}
 public async Task<IActionResult> OnPostReverseResultAsync(Guid id,CancellationToken t){ModelState.Clear();var r=await traceability.ReverseResultAsync(ResultReverse.OperationId,ResultReverse.ResultId,ResultReverse.ExpectedVersion,ResultReverse.Reason??"",ResultReverse.Pin,t);ResultReverse.Pin="";if(r.Success){TempData["Success"]="Resultado y consumo revertidos con historial.";return RedirectToPage(new{id,BatchId});}ModelState.AddModelError(string.Empty,r.Errors?.FirstOrDefault()??"No fue posible revertir el resultado.");return await InvalidPage(id,t);}
 public async Task<IActionResult> OnPostActionAsync(Guid id,CancellationToken t){ModelState.Clear();var c=new ProductionOrderActionCommand(Action.OperationId,id,Action.ExpectedVersion,Action.Pin,Action.Reason,Action.Quantity);var r=Action.Mode switch{"release"=>await service.ReleaseAsync(c,t),"pause"=>await service.PauseAsync(c,t),"resume"=>await service.ResumeAsync(c,t),"authorize"=>await service.AuthorizeAdditionalAsync(c,t),"close"=>await service.CloseAsync(c,t),"cancel"=>await service.CancelAsync(c,t),_=>new(ProductionCommandStatus.ValidationFailed,Errors:["Acción no válida."])};Action.Pin="";return await Finish(id,r,"Orden actualizada.",t);}
 public async Task<IActionResult> OnPostPlanningAsync(Guid id,CancellationToken t){ModelState.Clear();var targets=Planning.Targets.Select(x=>new ProductionPlanningTargetInput(x.PlanId,x.TargetKey)).ToArray();var r=await planning.ReviewAsync(new(Planning.OperationId,id,Planning.ExpectedVersion,targets,Planning.Reason??"",Planning.Pin),t);Planning.Pin="";if(r.Status==ProductionPlanningStatus.Success){TempData["Success"]="Planificación revisada y fotografiada.";return RedirectToPage(new{id});}ModelState.AddModelError(string.Empty,PlanningMessage(r));return await InvalidPage(id,t);}
 public async Task<IActionResult> OnPostMaterialAsync(Guid id,CancellationToken t){ModelState.Clear();var type=Material.Mode switch{"consume"=>ProductionMaterialOperationType.Consumption,"return"=>ProductionMaterialOperationType.WarehouseReturn,"supplier"=>ProductionMaterialOperationType.SupplierReturn,_=>ProductionMaterialOperationType.Consumption};var lines=Material.Lines.Where(x=>x.Selected&&x.Quantity>0).Select(x=>new ProductionMaterialSelection(x.IssueLinkId,x.Quantity)).ToArray();var r=await materials.ApplyAsync(new(Material.OperationId,id,Material.StageId,Material.ExpectedVersion,type,lines,Material.Pin,Material.DestinationLocationId,Material.Reference,Material.Notes,Material.ApproveSharedDestination),t);Material.Pin="";if(r.Status==ProductionMaterialStatus.Success){TempData["Success"]=type==ProductionMaterialOperationType.Consumption?"Material WIP consumido.":"Material WIP devuelto.";return RedirectToPage(new{id});}ModelState.AddModelError(string.Empty,MaterialMessage(r));return await InvalidPage(id,t);}
 public async Task<IActionResult> OnPostReverseMaterialAsync(Guid id,CancellationToken t){ModelState.Clear();var r=await materials.ReverseAsync(MaterialReverse.OperationId,MaterialReverse.MaterialOperationId,MaterialReverse.ExpectedVersion,MaterialReverse.Pin,MaterialReverse.Reason??"",t);MaterialReverse.Pin="";if(r.Status==ProductionMaterialStatus.Success){TempData["Success"]="Operación de material revertida.";return RedirectToPage(new{id});}ModelState.AddModelError(string.Empty,MaterialMessage(r));return await InvalidPage(id,t);}
 private async Task<IActionResult> Finish(Guid id,ProductionCommandResult r,string message,CancellationToken t){if(r.Status==ProductionCommandStatus.Success){TempData["Success"]=message;return RedirectToPage(new{id});}ModelState.AddModelError(string.Empty,Message(r));return await InvalidPage(id,t);}
 private async Task<PageResult> InvalidPage(Guid id,CancellationToken t){Process.Pin=Handoff.Pin=Warehouse.Pin=Action.Pin=Planning.Pin=Material.Pin=MaterialReverse.Pin="";await LoadAsync(id,t);return Page();}
 private async Task<bool> LoadAsync(Guid id,CancellationToken t){var o=await query.GetAsync(id,t);if(o is null)return false;Order=o;PlanningView=await planning.GetAsync(id,t);Shifts=await query.GetShiftsAsync(t);Destinations=await query.GetDestinationsAsync(t);MaterialIssues=await materials.GetIssuesAsync(id,t);MaterialOperations=await materials.GetOperationsAsync(id,t);Batches=await traceability.GetBatchesAsync(id,t);MaterialPlan=await traceability.GetPlanAsync(id,t);PendingDeliveries=await traceability.GetPendingDeliveriesAsync(id,t);if(BatchId is null&&!Request.Query.ContainsKey(nameof(BatchId)))BatchId=Batches.FirstOrDefault()?.Id;if(BatchId is Guid batchId){TraceLinks=await traceability.GetTraceAsync(batchId,t);BatchResults=await traceability.GetResultsAsync(batchId,t);}Action.ExpectedVersion=Planning.ExpectedVersion=Batch.ExpectedVersion=BatchResult.ExpectedVersion=PlanAdjustment.ExpectedVersion=ResultReverse.ExpectedVersion=o.Version;Handoff.ExpectedVersion=Warehouse.ExpectedVersion=o.Version;return true;}
 private static string Message(ProductionCommandResult r)=>r.Status switch{ProductionCommandStatus.InvalidPin=>"NIP inválido o usuario sin permiso.",ProductionCommandStatus.ConcurrencyConflict=>"La orden cambió mientras capturabas. Recarga y vuelve a revisar las cantidades.",ProductionCommandStatus.IdempotencyConflict=>"Esta operación ya se usó con datos distintos.",ProductionCommandStatus.RequiresLocationSharingConfirmation=>"La ubicación contiene otros productos; confirma desde el flujo de Entrada antes de continuar.",_=>r.ValidationErrors.FirstOrDefault()??"No fue posible registrar la operación."};
 private static string MaterialMessage(ProductionMaterialResult r)=>r.Status switch{ProductionMaterialStatus.InvalidPin=>"NIP inválido o usuario sin permiso.",ProductionMaterialStatus.ConcurrencyConflict=>"La orden cambió. Recarga y revisa los materiales pendientes.",ProductionMaterialStatus.IdempotencyConflict=>"Esta operación ya se utilizó con datos distintos.",_=>r.Errors?.FirstOrDefault()??"No fue posible procesar el material WIP."};
 private static string PlanningMessage(ProductionPlanningResult r)=>r.Status switch{ProductionPlanningStatus.InvalidPin=>"NIP ADMIN inválido.",ProductionPlanningStatus.ConcurrencyConflict=>"La orden cambió. Recarga e intenta nuevamente.",ProductionPlanningStatus.IdempotencyConflict=>"El identificador de la revisión ya se utilizó con otros datos.",ProductionPlanningStatus.NotFound=>"La orden no existe.",_=>r.Errors?.FirstOrDefault()??"No fue posible revisar la planificación."};
 public sealed class ProcessInput{public Guid OperationId{get;set;}=Guid.NewGuid();[Required]public Guid StageId{get;set;}[Required]public Guid ShiftId{get;set;}public bool IsRework{get;set;}[Range(typeof(decimal),"0.0001","99999999999999")]public decimal InputQuantity{get;set;}public decimal GoodQuantity{get;set;}public decimal ReworkQuantity{get;set;}public decimal ScrapQuantity{get;set;}[StringLength(500)]public string? Reason{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
 public sealed class HandoffInput{public Guid OperationId{get;set;}=Guid.NewGuid();public uint? ExpectedVersion{get;set;}[Required]public string Mode{get;set;}="deliver";[Required]public Guid SourceStageId{get;set;}[Required]public Guid TargetStageId{get;set;}public Guid? BatchId{get;set;}public Guid? DeliveryEventId{get;set;}[Range(typeof(decimal),"0.0001","99999999999999")]public decimal Quantity{get;set;}[StringLength(500)]public string? Reason{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
 public sealed class WarehouseInput{public Guid OperationId{get;set;}=Guid.NewGuid();public uint? ExpectedVersion{get;set;}[Required]public Guid FinalStageId{get;set;}public Guid? BatchId{get;set;}[Range(typeof(decimal),"0.0001","99999999999999")]public decimal Quantity{get;set;}[Required]public Guid DestinationLocationId{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
 public sealed class ActionInput{public Guid OperationId{get;set;}=Guid.NewGuid();[Required]public string Mode{get;set;}="release";public uint? ExpectedVersion{get;set;}public decimal Quantity{get;set;}[StringLength(500)]public string? Reason{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
 public sealed class PlanningInput{public Guid OperationId{get;set;}=Guid.NewGuid();public uint ExpectedVersion{get;set;}public List<PlanningTargetInput> Targets{get;set;}=[];[StringLength(500)]public string? Reason{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
 public sealed class PlanningTargetInput{public Guid PlanId{get;set;}public string? TargetKey{get;set;}}
 public sealed class MaterialInput{public Guid OperationId{get;set;}=Guid.NewGuid();public Guid StageId{get;set;}public uint ExpectedVersion{get;set;}public string Mode{get;set;}="consume";public List<MaterialLineInput> Lines{get;set;}=[];public Guid? DestinationLocationId{get;set;}public bool ApproveSharedDestination{get;set;}[StringLength(120)]public string? Reference{get;set;}[StringLength(500)]public string? Notes{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
 public sealed class MaterialLineInput{public bool Selected{get;set;}public Guid IssueLinkId{get;set;}public decimal Quantity{get;set;}}
 public sealed class MaterialReverseInput{public Guid OperationId{get;set;}=Guid.NewGuid();public Guid MaterialOperationId{get;set;}public uint ExpectedVersion{get;set;}[StringLength(500)]public string? Reason{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
 public sealed class BatchInput{public Guid OperationId{get;set;}=Guid.NewGuid();public decimal Quantity{get;set;}public uint ExpectedVersion{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
 public sealed class BatchResultInput{public Guid OperationId{get;set;}=Guid.NewGuid();public Guid BatchId{get;set;}public Guid StageId{get;set;}public Guid ShiftId{get;set;}public bool IsRework{get;set;}public decimal InputQuantity{get;set;}public decimal GoodQuantity{get;set;}public decimal ReworkQuantity{get;set;}public decimal ScrapQuantity{get;set;}public uint ExpectedVersion{get;set;}[StringLength(500)]public string? DifferenceReason{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";public List<BatchMaterialLineInput>Materials{get;set;}=[];}
 public sealed class BatchMaterialLineInput{public bool Selected{get;set;}public Guid IssueLinkId{get;set;}public decimal Quantity{get;set;}}
 public sealed class PlanAdjustmentInput{public Guid OperationId{get;set;}=Guid.NewGuid();public Guid PlanId{get;set;}public decimal Quantity{get;set;}public uint ExpectedVersion{get;set;}[StringLength(500)]public string? Reason{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
 public sealed class ResultReverseInput{public Guid OperationId{get;set;}=Guid.NewGuid();public Guid ResultId{get;set;}public uint ExpectedVersion{get;set;}[StringLength(500)]public string? Reason{get;set;}[Required,RegularExpression("^[0-9]{4,8}$")]public string Pin{get;set;}="";}
}
