// Uses HTML generated by WipSummaryRouteTests and local assets; no live application.
const { chromium } = require('playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '../..');
const output = path.join(root, 'artifacts/wip-summary');
const assets = path.join(root, 'src/WarehouseEPI.Web/wwwroot');

(async () => {
    const browser = await chromium.launch({ channel: 'msedge', headless: true });
    try {
        for (const language of ['es', 'en']) for (const theme of ['light', 'dark']) for (const width of [390, 900, 1280]) {
            const context = await browser.newContext({ javaScriptEnabled: false, reducedMotion: 'reduce', viewport: { width, height: 1000 } });
            const page = await context.newPage();
            await page.route('http://wip.test/**', async route => {
                const url = new URL(route.request().url());
                if (url.pathname === '/Reports/Wip') {
                    const attention = url.searchParams.get('attention') || 'all';
                    return route.fulfill({ contentType: 'text/html', path: path.join(output, 'fixtures', `wip-${language}-${attention}.html`) });
                }
                const relative = decodeURIComponent(url.pathname).replace(/\.[a-z0-9]{10}\.(css|js)$/, '.$1').replace(/^\//, '');
                const file = path.resolve(assets, relative);
                if (file.startsWith(assets + path.sep) && fs.existsSync(file) && fs.statSync(file).isFile()) return route.fulfill({ path: file });
                return route.fulfill({ status: 204 });
            });
            await page.goto('http://wip.test/Reports/Wip');
            assert.equal(await page.locator('#wip-sort').inputValue(), 'newest');
            const pending = page.locator('[data-wip-attention="pending"]');
            assert.equal(await pending.locator('strong').innerText(), '30');
            await pending.focus();
            assert.equal(await pending.evaluate(el => getComputedStyle(el).outlineStyle), 'solid');
            await page.keyboard.press('Tab');
            assert.equal(await page.evaluate(() => document.activeElement.dataset.wipAttention), 'aged');
            await page.keyboard.press('Enter');
            await page.waitForURL('**attention=aged**');
            assert.equal(await page.locator('#wip-sort').inputValue(), 'oldest');
            assert.equal(await page.locator('[data-wip-attention="aged"]').getAttribute('aria-current'), 'true');
            assert.equal(await page.locator('[data-wip-attention="aged"] small').innerText(), language === 'es' ? 'Seleccionado' : 'Selected');
            assert.equal(await page.locator('.wip-summary-units > div').count(), 4);
            assert.ok((await page.locator('.wip-summary-units dd').allTextContents()).includes('16'));
            await page.evaluate(theme => document.documentElement.setAttribute('data-bs-theme', theme), theme);
            for (const metric of await page.locator('[data-wip-attention]').all()) {
                const box = await metric.boundingBox();
                assert.ok(box.width >= 44 && box.height >= 44 && box.x >= 0 && box.x + box.width <= width + 1);
            }
            await page.locator('.wip-summary').screenshot({ path: path.join(output, `${language}-${theme}-${width}.png`) });
            await page.locator('[data-wip-attention="pending"]').click();
            await page.waitForURL('**attention=pending**');
            assert.ok((await page.locator('.wip-summary-units dd').allTextContents()).includes('42'));
            await page.locator('[data-wip-all]').click();
            await page.waitForURL(url => !url.searchParams.get('attention'));
            const query = new URL(page.url()).searchParams;
            assert.equal(query.get('search'), 'SUM-');
            assert.equal(query.get('from'), '2026-09-01');
            assert.equal(query.get('to'), '2026-10-09');
            assert.equal(query.get('sort'), 'oldest');
            assert.equal(query.get('pageNumber'), '1');
            assert.ok(query.get('wipAreaId'));
            await context.close();
        }
        console.log('WIP summary: 12 ES/EN, light/dark, responsive and keyboard scenarios passed without JavaScript.');
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
