// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseEPI.Infrastructure.Persistence;

#nullable disable

namespace WarehouseEPI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20260813185432_AddUnassignedUnit")]
    partial class AddUnassignedUnit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarehouseEPI.Core.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aisle")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("aisle");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_blocked");

                    b.Property<short?>("LevelNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("level_number");

                    b.Property<string>("PalletPosition")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("pallet_position");

                    b.Property<short?>("Shelf")
                        .HasColumnType("smallint")
                        .HasColumnName("shelf");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("locations", null, t =>
                        {
                            t.HasCheckConstraint("ck_locations_level", "level_number IS NULL OR level_number > 0");

                            t.HasCheckConstraint("ck_locations_shelf", "shelf IS NULL OR shelf > 0");
                        });
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsNegativeStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allows_negative_stock");

                    b.Property<short>("BaseUnitId")
                        .HasColumnType("smallint")
                        .HasColumnName("base_unit_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("external_reference");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("MinimumStock")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("minimum_stock");

                    b.Property<short?>("ProductClassId")
                        .HasColumnType("smallint")
                        .HasColumnName("product_class_id");

                    b.Property<short?>("ProductTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("product_type_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("sku");

                    b.Property<bool>("TracksExpiration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tracks_expiration");

                    b.Property<bool>("TracksLots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("tracks_lots");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("BaseUnitId");

                    b.HasIndex("ProductClassId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_expiration_requires_lots", "NOT tracks_expiration OR tracks_lots");

                            t.HasCheckConstraint("ck_products_external_reference_trimmed", "external_reference IS NULL OR (external_reference = btrim(external_reference) AND external_reference <> '')");

                            t.HasCheckConstraint("ck_products_minimum_stock", "minimum_stock >= 0");

                            t.HasCheckConstraint("ck_products_sku_normalized", "sku = upper(btrim(sku)) AND sku <> ''");
                        });
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.ProductBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Format")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("CODE_128")
                        .HasColumnName("format");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("is_primary = TRUE");

                    b.ToTable("product_barcodes", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_barcodes_format", "format IN ('CODE_128', 'EAN_13', 'EAN_8', 'UPC_A', 'UPC_E', 'QR', 'OTHER')");
                        });
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.ProductClass", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("product_classes", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_classes_code_normalized", "code = upper(btrim(code)) AND code <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "2-BBAGS",
                            IsActive = true,
                            Name = "2-BBAGS"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "AQUA",
                            IsActive = true,
                            Name = "AQUA"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "AQUATANK",
                            IsActive = true,
                            Name = "AQUATANK"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "BAYRIG",
                            IsActive = true,
                            Name = "BAYRIG"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "BCF",
                            IsActive = true,
                            Name = "BCF"
                        },
                        new
                        {
                            Id = (short)6,
                            Code = "BERMS",
                            IsActive = true,
                            Name = "BERMS"
                        },
                        new
                        {
                            Id = (short)7,
                            Code = "BIOSEAL",
                            IsActive = true,
                            Name = "BIOSEAL"
                        },
                        new
                        {
                            Id = (short)8,
                            Code = "BIOSEAL-EPI",
                            IsActive = true,
                            Name = "BIOSEAL-EPI"
                        },
                        new
                        {
                            Id = (short)9,
                            Code = "BODY BAGS",
                            IsActive = true,
                            Name = "BODY BAGS"
                        },
                        new
                        {
                            Id = (short)10,
                            Code = "BODY BAGS-HARD BAGS",
                            IsActive = true,
                            Name = "BODY BAGS-HARD BAGS"
                        },
                        new
                        {
                            Id = (short)11,
                            Code = "CBF",
                            IsActive = true,
                            Name = "CBF"
                        },
                        new
                        {
                            Id = (short)12,
                            Code = "DUMPSTER LINER",
                            IsActive = true,
                            Name = "DUMPSTER LINER"
                        },
                        new
                        {
                            Id = (short)13,
                            Code = "FC-HARDBAGS",
                            IsActive = true,
                            Name = "FC-HARDBAGS"
                        },
                        new
                        {
                            Id = (short)14,
                            Code = "IWM",
                            IsActive = true,
                            Name = "IWM"
                        },
                        new
                        {
                            Id = (short)15,
                            Code = "KPA",
                            IsActive = true,
                            Name = "KPA"
                        },
                        new
                        {
                            Id = (short)16,
                            Code = "MISC",
                            IsActive = true,
                            Name = "MISC"
                        },
                        new
                        {
                            Id = (short)17,
                            Code = "NUCLEAR BAGS",
                            IsActive = true,
                            Name = "NUCLEAR BAGS"
                        },
                        new
                        {
                            Id = (short)18,
                            Code = "PACKAGING",
                            IsActive = true,
                            Name = "PACKAGING"
                        },
                        new
                        {
                            Id = (short)19,
                            Code = "RAD BAGS",
                            IsActive = true,
                            Name = "RAD BAGS"
                        },
                        new
                        {
                            Id = (short)20,
                            Code = "RM",
                            IsActive = true,
                            Name = "RM"
                        },
                        new
                        {
                            Id = (short)21,
                            Code = "SPOUTED BAGS",
                            IsActive = true,
                            Name = "SPOUTED BAGS"
                        },
                        new
                        {
                            Id = (short)22,
                            Code = "SUB",
                            IsActive = true,
                            Name = "SUB"
                        },
                        new
                        {
                            Id = (short)23,
                            Code = "SUB-COMP",
                            IsActive = true,
                            Name = "SUB-COMP"
                        },
                        new
                        {
                            Id = (short)24,
                            Code = "SUBASS",
                            IsActive = true,
                            Name = "SUBASS"
                        },
                        new
                        {
                            Id = (short)25,
                            Code = "SUBASSEMBLY",
                            IsActive = true,
                            Name = "SUBASSEMBLY"
                        },
                        new
                        {
                            Id = (short)26,
                            Code = "UNDERGARMENTS",
                            IsActive = true,
                            Name = "UNDERGARMENTS"
                        });
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.ProductType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("product_types", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_types_code_normalized", "code = upper(btrim(code)) AND code <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "FG",
                            IsActive = true,
                            Name = "Producto terminado"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "RAW",
                            IsActive = true,
                            Name = "Materia prima"
                        });
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.Role", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "ADMIN",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "OPERATOR",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Operador"
                        });
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.Unit", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<bool>("AllowsDecimals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("allows_decimals");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("units", null, t =>
                        {
                            t.HasCheckConstraint("ck_units_code_normalized", "code = upper(btrim(code)) AND code <> ''");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            AllowsDecimals = true,
                            Code = "EA",
                            IsActive = true,
                            Name = "Pieza"
                        },
                        new
                        {
                            Id = (short)2,
                            AllowsDecimals = true,
                            Code = "BX",
                            IsActive = true,
                            Name = "Caja"
                        },
                        new
                        {
                            Id = (short)3,
                            AllowsDecimals = true,
                            Code = "BDL",
                            IsActive = true,
                            Name = "Bulto"
                        },
                        new
                        {
                            Id = (short)4,
                            AllowsDecimals = true,
                            Code = "CTN",
                            IsActive = true,
                            Name = "Caja de embarque"
                        },
                        new
                        {
                            Id = (short)5,
                            AllowsDecimals = true,
                            Code = "FT",
                            IsActive = true,
                            Name = "Pie"
                        },
                        new
                        {
                            Id = (short)6,
                            AllowsDecimals = true,
                            Code = "GAL",
                            IsActive = true,
                            Name = "Galón"
                        },
                        new
                        {
                            Id = (short)7,
                            AllowsDecimals = true,
                            Code = "5GAL",
                            IsActive = true,
                            Name = "Recipiente de 5 galones"
                        },
                        new
                        {
                            Id = (short)8,
                            AllowsDecimals = true,
                            Code = "3GANG",
                            IsActive = true,
                            Name = "Grupo de 3"
                        },
                        new
                        {
                            Id = (short)9,
                            AllowsDecimals = true,
                            Code = "KT",
                            IsActive = true,
                            Name = "Kit"
                        },
                        new
                        {
                            Id = (short)10,
                            AllowsDecimals = true,
                            Code = "PR",
                            IsActive = true,
                            Name = "Par"
                        },
                        new
                        {
                            Id = (short)11,
                            AllowsDecimals = true,
                            Code = "LB",
                            IsActive = true,
                            Name = "Libra"
                        },
                        new
                        {
                            Id = (short)12,
                            AllowsDecimals = true,
                            Code = "RL",
                            IsActive = true,
                            Name = "Rollo"
                        },
                        new
                        {
                            Id = (short)13,
                            AllowsDecimals = true,
                            Code = "SQFT",
                            IsActive = true,
                            Name = "Pie cuadrado"
                        },
                        new
                        {
                            Id = (short)14,
                            AllowsDecimals = true,
                            Code = "MSI",
                            IsActive = true,
                            Name = "Mil pulgadas cuadradas"
                        },
                        new
                        {
                            Id = (short)15,
                            AllowsDecimals = true,
                            Code = "YD",
                            IsActive = true,
                            Name = "Yarda"
                        },
                        new
                        {
                            Id = (short)16,
                            AllowsDecimals = true,
                            Code = "IN",
                            IsActive = true,
                            Name = "Pulgada"
                        },
                        new
                        {
                            Id = (short)17,
                            AllowsDecimals = true,
                            Code = "OZ",
                            IsActive = true,
                            Name = "Onza"
                        },
                        new
                        {
                            Id = (short)18,
                            AllowsDecimals = true,
                            Code = "UNASSIGNED",
                            IsActive = true,
                            Name = "Sin asignar"
                        });
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pin_hash");

                    b.Property<string>("PinLookup")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("pin_lookup")
                        .IsFixedLength();

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("PinLookup")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.Product", b =>
                {
                    b.HasOne("WarehouseEPI.Core.Entities.Unit", "BaseUnit")
                        .WithMany("Products")
                        .HasForeignKey("BaseUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehouseEPI.Core.Entities.ProductClass", "ProductClass")
                        .WithMany("Products")
                        .HasForeignKey("ProductClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WarehouseEPI.Core.Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseUnit");

                    b.Navigation("ProductClass");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.ProductBarcode", b =>
                {
                    b.HasOne("WarehouseEPI.Core.Entities.Product", "Product")
                        .WithMany("Barcodes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.User", b =>
                {
                    b.HasOne("WarehouseEPI.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.Product", b =>
                {
                    b.Navigation("Barcodes");
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.ProductClass", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WarehouseEPI.Core.Entities.Unit", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
