// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WarehouseEPI.Infrastructure.Persistence;

#nullable disable

namespace WarehouseEPI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20260910185035_ProductionMaterialOrderLinks")]
    partial class ProductionMaterialOrderLinks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
